version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lufy-postgres
    environment:
      POSTGRES_DB: lufy_db
      POSTGRES_USER: lufy_user
      POSTGRES_PASSWORD: lufy_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U lufy_user -d lufy_db']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
